### ISSUE TITLE
Clock characters being cropped

### ISSUE THREAD

**Issue by Thenoman** [gregorkuznik/mtg-full-screen-timer#13]
When using the timer in Full Screen mode in Chrome on a Macbook Pro the characters are being truncated and cropped (see screenshot).
<img width="1280" alt="screen shot 2017-09-19 at 09 22 33" src="https://user-images.githubusercontent.com/32091771/30582713-a3ddd61e-9d1c-11e7-9922-9490f50ef8b5.png">

**Comment by neyko5** [comment]
Thank you for your report @Thenoman! We have noticed this ourselves on Mac due to different font used.
